In [15]:
#1,Display Fibonacci series up to 10 terms
l1=int(input("enter your number for series"))
first=0
second=1
for i in range(l1):
    print(first)
    temp=first
    first=second
    second=temp+first

enter your number for series10
0
1
1
2
3
5
8
13
21
34


In [12]:
#2,Use a loop to display elements from a given list present at odd index positions
n=[12,34,56,43,23,45,65,6,7,8]
for i in range(1,len(n)):
    if i%2!=0:
        print(n[i])

34
43
45
6
8


In [75]:
#3,Create a recursive function
def count(n):
    print(n)
    if n==0:
        return
    else:
        count(n-1)
count(4)        

4
3
2
1
0


In [9]:
#4,Create a list by picking an odd-index item from the first list and even index items from the second
list1=[2,34,5,6,7,8,9,10,33,44]
for i in range(0,len(list1)):
    if i%2==0:
        print(list1[i])

2
5
7
9
33


In [5]:
list1=[2,34,5,6,7,8,9,10,33,44]
for i in range(1,len(list1)):
    if i%2!=0:
        print(list1[i])

34
6
8
10
44


In [41]:
#5,Checks if one set is a subset or superset of another set. If found, delete all elements from that set

s1={10,20,30,40,50}
s2={10,20,30}
if set(s2).issubset(s1) or set(s2).issuperset(s1):
    s2=s2.clear()
    print(s2)

None


In [78]:
#6,Change value of a key in a nested dictionary
dict1={"name":"Rajiv","city":"Delhi","country"="india"}
#ict1}"name":Raju"]
dict1("name":"raju")

SyntaxError: invalid syntax (2652368826.py, line 2)

In [72]:
dict1={"name":"Rajiv","city":"Delhi","country"="india"}
dict1.update(["name"="Rahul"])


SyntaxError: invalid syntax (4042352011.py, line 1)

In [45]:
#7.Create a 4X2 integer array and Prints its attributes
import numpy as np
arr1=np.array([[2,3],[4,5],[6,7],[8,9]])
arr1

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [68]:
#8,Following is the provided numPy array. Return array of items by taking the third column from all rows
arr1=np.array([[2,4,5,6,6,7],[4,5,64,32,1,1],[34,54,32,12,22,2],[33,44,55,66,77,88],[22,21,23,45,43,25]])
#arr1
arr1[0:,2:]

array([[ 5,  6,  6,  7],
       [64, 32,  1,  1],
       [32, 12, 22,  2],
       [55, 66, 77, 88],
       [23, 45, 43, 25]])

In [128]:
#9,Create a result array by adding the following two NumPy arrays. Next, 
# modify the result array by calculating the square of each element
arr1=np.array([[2,3,4,5],[4,5,6,7],[3,4,5,6]])
arr2=np.array([[34,5,6,7],[6,7,8,9],[8,9,8,9]])
print(arr1)
print()
print(arr2)

[[2 3 4 5]
 [4 5 6 7]
 [3 4 5 6]]

[[34  5  6  7]
 [ 6  7  8  9]
 [ 8  9  8  9]]


In [124]:
result_array=arr1+arr2
result_array

array([[36,  8, 10, 12],
       [10, 12, 14, 16],
       [11, 13, 13, 15]])

In [126]:
for i in result_array:
    print(i**2)

[1296   64  100  144]
[100 144 196 256]
[121 169 169 225]


In [108]:
# 10,Create a Python set such that it shows the element from both lists in a pair
l1=[2,4,5,3,2,4,5]
l2=[1,1,1,1,1,1,1]
for i in l1:
    for j in l2:
        result=l1[i],l2[j]
    print(result)        

(5, 1)
(2, 1)
(4, 1)
(3, 1)
(5, 1)
(2, 1)
(4, 1)


In [56]:
#11.How to get the items of series A not present in series B?
ser1={12,34,33,22,11,25,32}
ser2={11,23,34,33}
set(ser1.difference(ser2))

{12, 22, 25, 32}

In [ ]:
#12,How to keep only top 2 most frequent values as it is and replace everything else as ‘Other’?

In [116]:
l1=[2,5,5,3,2,4,6]
count=0
for i in range(0,len(l1)):
    
        print(i)

[2, 5, 5, 3, 2, 4, 6]


TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [89]:
#13, How to find the positions of numbers that are multiples of 3 from a series?
list1=(2,34,5,6,7,8,9,10,33,44)
for i in range(1,len(list1)):
    if list1[i]%3==0:
        print(i)

3
6
8


In [129]:
list1=[2,34,5,6,7,8,9,10,33,44]
for i in range(1,len(list1)):
    if list1[i]%3==0:
        print(i)

3
6
8
